create table if not exists public.training_professional_categories (
  id bigint generated by default as identity primary key,
  training_id uuid not null references public.trainings (id) on delete cascade,
  category text not null,
  created_at timestamptz not null default now(),
  unique (training_id, category)
);

create index if not exists training_professional_categories_training_id_idx
  on public.training_professional_categories (training_id);
