create table if not exists public.training_locations (
  id bigint generated by default as identity primary key,
  training_id uuid not null references public.trainings (id) on delete cascade,
  location text not null,
  created_at timestamptz not null default now(),
  unique (training_id, location)
);

create index if not exists training_locations_training_id_idx
  on public.training_locations (training_id);
