create table if not exists public.training_sectors (
  id bigint generated by default as identity primary key,
  training_id uuid not null references public.trainings (id) on delete cascade,
  sector text not null,
  created_at timestamptz not null default now(),
  unique (training_id, sector)
);

create index if not exists training_sectors_training_id_idx
  on public.training_sectors (training_id);
